[build-system]
requires = ["hatchling>=1.5.0", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "globato"
description = "A suite of specialized data processors (Multibeam, Lidar, Raster), etc. for the Fetchez ecosystem."
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]
requires-python = ">=3.12"
authors = [{ name = "Matthew Love", email = "matthew.love@colorado.edu" }]
maintainers = [
    {name = "Matthew Love", email = "matthew.love@colorado.edu"},
]
keywords = ["geospatial", "fetchez", "multibeam", "lidar", "etl"]
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: GIS',
]

dependencies = [
    "fetchez>=0.5.6",
    "transformez>=0.3.2",
    "numpy>1.24",
    "scipy",
    "shapely",
    "laspy[lazrs,laszip]",
    "rasterio>1.4.0",
    "fiona",
    "pandas",
    "pyproj>3.6.1",
    "pyshp",
    "matplotlib",
    "h5py",
    "click",
    "pyyaml",
    "requests",
]

[project.optional-dependencies]
gmt = ["pygmt"]
gdal = ["gdal"]
# verde = ["verde"]
# naturalneighbor = ["naturalneighbor"]
interpolations = ["verde", "pykrige"]
ml = ["scikit-learn"]
h3 = ["h3"]

full = ["globato[gmt,gdal,interpolations,ml]"]

[dependency-groups]
dev = [
    "mypy",
]
test = [
    "pytest",
    "pytest-cov",
    "requests-mock",
]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints>=2.0.1",
    "sphinx-argparse-cli",
    "pydata-sphinx-theme",
    "myst-parser",
]

[project.urls]
Homepage = "https://github.com/continuous-dems/globato"
Repository = "https://github.com/continuous-dems/globato"

[project.entry-points."fetchez.modules"]
globato_modules = "globato.modules"

[project.entry-points."fetchez.hooks"]
globato_hooks = "globato.hooks"

[project.entry-points."fetchez.schemas"]
globato_schemas = "globato.schemas"

[project.entry-points."fetchez.recipes"]
globato_recipes = "globato.recipes"

[project.entry-points."fetchez.presets"]
globato_presets = "globato.presets"

[project.entry-points."fetchez.bundles"]
globato_bundles = "globato.bundles"

# [project.entry-points."fetchez.plugins"]
# globato = "globato"

[project.scripts]
globato = "globato.cli:cli"

# --- Build configuration ---

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.version]
path = "src/globato/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/globato"]

[tool.hatch.build.targets.sdist]
include = [
  "src/globato",
  "tests",
  "CHANGELOG.md",
  "CITATION.cff",
  "CONTRIBUTING.md",
  "AUTHORS.md",
]
exclude = [
  ".github",
]

# # --- Devtools configuration ---

# [tool.mypy]
# mypy_path = "src"
# packages = ["globato"]
# python_version = "3.12"
# disable_error_code = ["import-untyped"]
# # strict = true

# [[tool.mypy.overrides]]
# module = [
#     "matplotlib.*",
#     "rasterio.*",
#     "scipy.*",
#     "pyproj.*",
#     "fetchez.*",
# ]
# ignore_missing_imports = true
# follow_untyped_imports = true
